# Generated by Django 3.1.7 on 2021-02-26 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('created', models.DateTimeField(auto_created=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='商品标题')),
                ('describe', models.TextField(verbose_name='商品描述')),
                ('picture', models.ImageField(null=True, upload_to='commodity', verbose_name='商品图片')),
                ('cost', models.IntegerField(verbose_name='商品需要花费的积分')),
                ('exchanged', models.IntegerField(default=0, verbose_name='已经兑换了的人数')),
                ('limit', models.IntegerField(default=0, verbose_name='商品限额，0为不限制')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRecord',
            fields=[
                ('created', models.DateTimeField(auto_created=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('help_text', models.CharField(max_length=100)),
                ('cost', models.IntegerField(verbose_name='用户购买商品花费的积分')),
                ('commodity', models.ForeignKey(help_text='用户购买的商品', on_delete=django.db.models.deletion.CASCADE, to='store.commodity')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
