# Generated by Django 3.1.7 on 2021-02-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
