# Generated by Django 3.1.7 on 2021-03-05 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210303_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
