# Generated by Django 3.1.7 on 2021-03-06 11:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210305_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='截止日期'),
            preserve_default=False,
        ),
    ]
