# Generated by Django 3.1.7 on 2021-03-07 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_commodity_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserecord',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
