# Generated by Django 3.1.7 on 2021-03-12 03:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_purchaserecord_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commodity',
            name='deadline',
            field=models.DateTimeField(verbose_name='截止时间'),
        ),
    ]
