image: python:3.7-buster

stages:
  - test

test:
  stage: test
  script:
    - apt-get update -qy
    - apt-get install -y python3-dev python3-pip
    - cd youth-learning-server
    - pip3 install -r requirements.txt
    - python3 manage.py test
