# Generated by Django 3.1 on 2020-08-23 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPeriod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('season', models.IntegerField(db_index=True, verbose_name='青年大学习季数')),
                ('period', models.IntegerField(db_index=True, verbose_name='青年大学习期数')),
                ('name', models.CharField(max_length=50, verbose_name='青年大学习期数名称')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudyRecording',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('study_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.studyperiod')),
            ],
        ),
    ]
