# Generated by Django 3.1 on 2020-08-24 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study', '0002_studyrecording_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyperiod',
            name='url',
            field=models.CharField(default='', max_length=100, verbose_name='青年大学习视频链接'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='studyrecording',
            unique_together={('user_id', 'study_id')},
        ),
        migrations.CreateModel(
            name='StudyScore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(verbose_name='获得的积分')),
                ('detail', models.CharField(max_length=50, verbose_name='说明')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('study_recording', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='study.studyrecording')),
            ],
        ),
    ]
