# Generated by Django 3.1 on 2020-08-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_auto_20200824_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyrecording',
            name='detail',
            field=models.CharField(default='', max_length=50, verbose_name='说明'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studyrecording',
            name='score',
            field=models.IntegerField(default=0, verbose_name='获得的积分'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='StudyScore',
        ),
    ]
