# Generated by Django 3.1.1 on 2020-11-17 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0005_auto_20200925_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyperiod',
            name='time',
            field=models.IntegerField(default=300, verbose_name='青年大学习视频秒数'),
            preserve_default=False,
        ),
    ]
