# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='api.proto',
  package='credit.service.v1',
  syntax='proto3',
  serialized_options=b'Z\003api',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tapi.proto\x12\x11\x63redit.service.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\"R\n\x05Score\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\r\n\x05score\x18\x03 \x01(\x01\x12\x0f\n\x07\x63omment\x18\x04 \x01(\t\x12\x0c\n\x04time\x18\x05 \x01(\x03\"2\n\x06Scores\x12(\n\x06scores\x18\x01 \x03(\x0b\x32\x18.credit.service.v1.Score\">\n\x0b\x41\x64\x64ScoreReq\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x01\x12\x0f\n\x07\x63omment\x18\x03 \x01(\t\";\n\tGetAllReq\x12\r\n\x05limit\x18\x01 \x01(\x04\x12\x0e\n\x06offset\x18\x02 \x01(\x04\x12\x0f\n\x07user_id\x18\x03 \x01(\t\"\x1e\n\x0bGetScoreReq\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"\x1e\n\x0eGetScoreOldReq\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\"\x19\n\x08SumScore\x12\r\n\x05score\x18\x01 \x01(\x01\x32\xaf\x02\n\x06\x43redit\x12\x44\n\x08\x41\x64\x64Score\x12\x1e.credit.service.v1.AddScoreReq\x1a\x16.google.protobuf.Empty\"\x00\x12\x43\n\x06GetAll\x12\x1c.credit.service.v1.GetAllReq\x1a\x19.credit.service.v1.Scores\"\x00\x12I\n\x08GetScore\x12\x1e.credit.service.v1.GetScoreReq\x1a\x1b.credit.service.v1.SumScore\"\x00\x12O\n\x0bGetScoreOld\x12!.credit.service.v1.GetScoreOldReq\x1a\x1b.credit.service.v1.SumScore\"\x00\x42\x05Z\x03\x61pib\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,google_dot_api_dot_annotations__pb2.DESCRIPTOR,])




_SCORE = _descriptor.Descriptor(
  name='Score',
  full_name='credit.service.v1.Score',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='credit.service.v1.Score.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='credit.service.v1.Score.user_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='score', full_name='credit.service.v1.Score.score', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='comment', full_name='credit.service.v1.Score.comment', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time', full_name='credit.service.v1.Score.time', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=173,
)


_SCORES = _descriptor.Descriptor(
  name='Scores',
  full_name='credit.service.v1.Scores',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='scores', full_name='credit.service.v1.Scores.scores', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=225,
)


_ADDSCOREREQ = _descriptor.Descriptor(
  name='AddScoreReq',
  full_name='credit.service.v1.AddScoreReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='credit.service.v1.AddScoreReq.user_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='score', full_name='credit.service.v1.AddScoreReq.score', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='comment', full_name='credit.service.v1.AddScoreReq.comment', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=227,
  serialized_end=289,
)


_GETALLREQ = _descriptor.Descriptor(
  name='GetAllReq',
  full_name='credit.service.v1.GetAllReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='limit', full_name='credit.service.v1.GetAllReq.limit', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='offset', full_name='credit.service.v1.GetAllReq.offset', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='credit.service.v1.GetAllReq.user_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=291,
  serialized_end=350,
)


_GETSCOREREQ = _descriptor.Descriptor(
  name='GetScoreReq',
  full_name='credit.service.v1.GetScoreReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='credit.service.v1.GetScoreReq.user_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=352,
  serialized_end=382,
)


_GETSCOREOLDREQ = _descriptor.Descriptor(
  name='GetScoreOldReq',
  full_name='credit.service.v1.GetScoreOldReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='credit.service.v1.GetScoreOldReq.code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=384,
  serialized_end=414,
)


_SUMSCORE = _descriptor.Descriptor(
  name='SumScore',
  full_name='credit.service.v1.SumScore',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='score', full_name='credit.service.v1.SumScore.score', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=416,
  serialized_end=441,
)

_SCORES.fields_by_name['scores'].message_type = _SCORE
DESCRIPTOR.message_types_by_name['Score'] = _SCORE
DESCRIPTOR.message_types_by_name['Scores'] = _SCORES
DESCRIPTOR.message_types_by_name['AddScoreReq'] = _ADDSCOREREQ
DESCRIPTOR.message_types_by_name['GetAllReq'] = _GETALLREQ
DESCRIPTOR.message_types_by_name['GetScoreReq'] = _GETSCOREREQ
DESCRIPTOR.message_types_by_name['GetScoreOldReq'] = _GETSCOREOLDREQ
DESCRIPTOR.message_types_by_name['SumScore'] = _SUMSCORE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Score = _reflection.GeneratedProtocolMessageType('Score', (_message.Message,), {
  'DESCRIPTOR' : _SCORE,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:credit.service.v1.Score)
  })
_sym_db.RegisterMessage(Score)

Scores = _reflection.GeneratedProtocolMessageType('Scores', (_message.Message,), {
  'DESCRIPTOR' : _SCORES,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:credit.service.v1.Scores)
  })
_sym_db.RegisterMessage(Scores)

AddScoreReq = _reflection.GeneratedProtocolMessageType('AddScoreReq', (_message.Message,), {
  'DESCRIPTOR' : _ADDSCOREREQ,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:credit.service.v1.AddScoreReq)
  })
_sym_db.RegisterMessage(AddScoreReq)

GetAllReq = _reflection.GeneratedProtocolMessageType('GetAllReq', (_message.Message,), {
  'DESCRIPTOR' : _GETALLREQ,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:credit.service.v1.GetAllReq)
  })
_sym_db.RegisterMessage(GetAllReq)

GetScoreReq = _reflection.GeneratedProtocolMessageType('GetScoreReq', (_message.Message,), {
  'DESCRIPTOR' : _GETSCOREREQ,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:credit.service.v1.GetScoreReq)
  })
_sym_db.RegisterMessage(GetScoreReq)

GetScoreOldReq = _reflection.GeneratedProtocolMessageType('GetScoreOldReq', (_message.Message,), {
  'DESCRIPTOR' : _GETSCOREOLDREQ,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:credit.service.v1.GetScoreOldReq)
  })
_sym_db.RegisterMessage(GetScoreOldReq)

SumScore = _reflection.GeneratedProtocolMessageType('SumScore', (_message.Message,), {
  'DESCRIPTOR' : _SUMSCORE,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:credit.service.v1.SumScore)
  })
_sym_db.RegisterMessage(SumScore)


DESCRIPTOR._options = None

_CREDIT = _descriptor.ServiceDescriptor(
  name='Credit',
  full_name='credit.service.v1.Credit',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=444,
  serialized_end=747,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddScore',
    full_name='credit.service.v1.Credit.AddScore',
    index=0,
    containing_service=None,
    input_type=_ADDSCOREREQ,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetAll',
    full_name='credit.service.v1.Credit.GetAll',
    index=1,
    containing_service=None,
    input_type=_GETALLREQ,
    output_type=_SCORES,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetScore',
    full_name='credit.service.v1.Credit.GetScore',
    index=2,
    containing_service=None,
    input_type=_GETSCOREREQ,
    output_type=_SUMSCORE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetScoreOld',
    full_name='credit.service.v1.Credit.GetScoreOld',
    index=3,
    containing_service=None,
    input_type=_GETSCOREOLDREQ,
    output_type=_SUMSCORE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CREDIT)

DESCRIPTOR.services_by_name['Credit'] = _CREDIT

# @@protoc_insertion_point(module_scope)
