# Generated by Django 3.1 on 2020-08-23 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_study',
            field=models.IntegerField(default=0, verbose_name='总学习期数'),
        ),
        migrations.AlterField(
            model_name='leaguebranch',
            name='college',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='user.college', verbose_name='学院'),
            preserve_default=False,
        ),
    ]
