# Generated by Django 3.1 on 2020-08-24 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_total_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='college_name', to='user.college', verbose_name='学院'),
        ),
        migrations.AlterField(
            model_name='user',
            name='league_branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='league_branch_name', to='user.leaguebranch', verbose_name='团支部'),
        ),
    ]
