# Generated by Django 3.1 on 2020-09-25 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200825_0631'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leaguebranch',
            unique_together={('name', 'college')},
        ),
    ]
